# Generated by Django 2.0.5 on 2018-06-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('commitDate', models.DateTimeField(auto_now=True)),
                ('pubDate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
