# Generated by Django 2.0.5 on 2018-06-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180616_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Gutech', max_length=20),
        ),
    ]
