# Generated by Django 2.0.5 on 2018-09-02 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postcomments_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='pubDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 18, 56, 39, 570040)),
        ),
    ]
