# Generated by Django 2.0.5 on 2018-09-08 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180902_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='pubDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 8, 21, 14, 8, 531563)),
        ),
    ]
