# Generated by Django 2.0.5 on 2018-09-10 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180908_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='pubDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 10, 7, 23, 45, 788185)),
        ),
    ]
